supermarket/apps/goods/urls.py
from django.conf.urls import url

from goods.views import CityView, SchoolView, TidingsView, RechargeView, DiscountView, SpeedView, \
    CategoryView, ShopView, DetailView

urlpatterns = [
    url(r'^$', ShopView.as_view(), name='超市首页'),
    url(r'^city/$', CityView.as_view(), name='城市'),
    url(r'^school/$', SchoolView.as_view(), name='校区'),
    url(r'tidings/$', TidingsView.as_view(), name='消息中心'),
    url(r"^recharge", RechargeView.as_view(), name='充值中心'),
    url(r'^discount/$', DiscountView.as_view(), name='红包'),
    url(r'^speed/$', SpeedView.as_view(), name='零食飞速'),
    url(r'^category/(?P<cate_id>\d*)_{1}(?P<order>\d?)$', CategoryView.as_view(), name='商品列表'),
    url(r'^detail/(?P<id>\d+)$', DetailView.as_view(), name='商品详情'),
]

supermarket/apps/orders/urls.py
from django.conf.urls import url

from orders.views import ReOrder, ShowOrder, Pay

urlpatterns = [
    url(r'^reorder/$',ReOrder.as_view(),name='确认订单'),
    url(r'^order/$',ShowOrder.as_view(),name='确认支付'),
    url(r'^pay/$',Pay.as_view(),name='支付结果')
]

supermarket/apps/shopcart/urls.py
from django.conf.urls import url

from shopcart.views import ShopCartView,  AddShopcartView

urlpatterns = [
    url(r'^list/$',ShopCartView.as_view(),name='购物车'),
    url(r'^add/$',AddShopcartView.as_view(),name='添加购物车'),
]

supermarket/apps/user/urls.py
from django.conf.urls import url

from user.views import RegisterView, LoginView, CenterView, MyInfoView, safe, RePassView, SendMailView, AddressView, \
    AddressList, ForgetView

urlpatterns = [
    url(r'^reg$', RegisterView.as_view(), name='注册'),
    url(r'^login$', LoginView.as_view(), name='登录'),
    url(r'^center', CenterView.as_view(), name='个人中心'),
    url(r'^myinfo', MyInfoView.as_view(), name='个人资料'),
    url(r'^safe', safe, name='安全设置'),
    url(r'^address', AddressView.as_view(), name='收货地址添加'),
    url(r'^add_list',AddressList.as_view(),name='收货地址'),
    url(r'^sendmail', SendMailView.as_view(), name='发送信息'),
    url(r'^forget', ForgetView.as_view(), name='忘记密码'),
    url(r'^repass', RePassView.as_view(), name='修改密码'),
]

supermarket/supermarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import ShopView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^orders/', include('orders.urls', namespace='order')),
    url(r'^shopcart/', include('shopcart.urls', namespace='shopcart')),
    url(r"^$", ShopView.as_view(), name='首页'),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls',namespace='search')),
]

supermarket/apps/goods/models.py
from django.db import models

# Create your models here.
from db.base_model import BaseModel
from ckeditor_uploader.fields import RichTextUploadingField


# 商品分类表
class Classification(BaseModel):
    classification_name = models.CharField(max_length=100,
                                           verbose_name='分类名')
    introduction = models.TextField(null=True,
                                    blank=True,
                                    verbose_name='简介')
    order = models.SmallIntegerField(default=0,
                                     verbose_name="排序")

    def __str__(self):
        return self.classification_name

    class Meta:
        verbose_name = '商品分类管理'
        verbose_name_plural = verbose_name


# 商品单位表
class Conversion(BaseModel):
    conversion_name = models.CharField(max_length=100, verbose_name='单位名')

    def __str__(self):
        return self.conversion_name

    class Meta:
        verbose_name = '商品单位管理'
        verbose_name_plural = verbose_name


# 商品SKU表
class GoodsSKU(BaseModel):
    is_on_sale_choices = (
        (False, "下架"),
        (True, "上架"),
    )
    sku_name = models.CharField(max_length=150,
                                verbose_name='商品SKU名')
    introduce = models.TextField(null=True,
                                 blank=True,
                                 verbose_name='简介')
    price = models.DecimalField(max_digits=9,
                                decimal_places=2,
                                default=0,
                                verbose_name='价格')
    conversion = models.ForeignKey(to='Conversion',
                                   verbose_name='单位')
    tock = models.CharField(max_length=150,
                            default=0,
                            verbose_name='库存')
    sale = models.CharField(max_length=160,
                            default=0,
                            verbose_name='销量')
    logo = models.ImageField(upload_to='goods/%Y%m%d',
                             verbose_name='封面图片')
    is_on_sale = models.BooleanField(verbose_name="是否上架",
                                     choices=is_on_sale_choices,
                                     default=False)
    classification = models.ForeignKey(to='Classification',
                                       verbose_name='商品分类')
    goods_spu = models.ForeignKey(to='GoodsSPU',
                                  verbose_name='商品SPU')

    def __str__(self):
        return self.sku_name

    class Meta:
        verbose_name = '商品SKU管理'
        verbose_name_plural = verbose_name


# 商品SPU表
class GoodsSPU(BaseModel):
    spu_name = models.CharField(max_length=100,
                                verbose_name='商品SPU名')
    details = RichTextUploadingField(verbose_name='详情')

    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = '商品SPU管理'
        verbose_name_plural = verbose_name


# 商品图片表
class GoodsPicture(BaseModel):
    picture_address = models.ImageField(verbose_name='相册图片地址',
                                        upload_to='goods_gallery/%Y%m/%d')
    commodity = models.ForeignKey(to='GoodsSKU',
                                  verbose_name='商品SKU')

    def __str__(self):
        return "商品相册:{}".format(self.picture_address.name)

    class Meta:
        verbose_name = '商品图片管理'
        verbose_name_plural = verbose_name


# 首页轮播
class Banner(BaseModel):
    name = models.CharField(verbose_name="轮播活动名",
                            max_length=150,
                            )
    img_url = models.ImageField(verbose_name='轮播图片地址',
                                upload_to='banner/%Y%m/%d'
                                )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )

    goods_sku = models.ForeignKey(to="GoodsSKU", verbose_name="商品SKU")

    class Meta:
        verbose_name = "轮播管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 首页活动
class Activity(BaseModel):
    title = models.CharField(verbose_name='活动名称', max_length=150)
    img_url = models.ImageField(verbose_name='活动图片地址',
                                upload_to='activity/%Y%m/%d'
                                )
    url_site = models.URLField(verbose_name='活动的url地址', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动管理"
        verbose_name_plural = verbose_name


# 首页活动专区
class ActivityZone(BaseModel):
    is_on_sale_choices = (
        (False, "下架"),
        (True, "上架"),
    )
    title = models.CharField(verbose_name='活动专区名称', max_length=150)
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )
    is_on_sale = models.BooleanField(verbose_name="上否上线",
                                     choices=is_on_sale_choices,
                                     default=0,
                                     )
    goods_sku = models.ManyToManyField(to="GoodsSKU", verbose_name="商品")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name

supermarket/apps/goods/views.py
from django.shortcuts import render
from django.views import View


from goods.models import GoodsSKU, Classification, Banner
from shopcart.helper import get_cart_count

# 首页
class ShopView(View):
    def get(self, request):
        banner = Banner.objects.all()
        goods_sku = GoodsSKU.objects.filter(is_delete=False)
        context={
            'banner':banner,
            'goods_sku':goods_sku
        }
        return render(request, 'goods/index.html',context=context)

    def post(self, request):
        pass


# 城市
class CityView(View):
    def get(self, request):
        return render(request, 'goods/city.html')

    def post(self, request):
        pass


# 校区
class SchoolView(View):
    def get(self, request):
        return render(request, 'goods/village.html')

    def post(self, request):
        pass


# 消息
class TidingsView(View):
    def get(self, request):
        return render(request, 'goods/village.html')

    def post(self, request):
        pass


# 充值
class RechargeView(View):
    def get(self, request):
        return render(request, 'goods/recharge.html')

    def post(self, request):
        pass


# 红包
class DiscountView(View):
    def get(self, request):
        return render(request, 'goods/yhq.html')

    def post(self, request):
        pass


# 零食飞速
class SpeedView(View):
    def get(self, request):
        return render(request, 'goods/speed.html')

    def post(self, request):
        pass


# 商品详情
class DetailView(View):
    def get(self, request, id):
        goods_sku = GoodsSKU.objects.get(pk=id)
        cart_count = get_cart_count(request)
        context = {
            'goods_sku': goods_sku,
            'cart_count':cart_count
        }
        return render(request, 'goods/detail.html', context=context)


# 商品列表
class CategoryView(View):
    def get(self, request, cate_id, order):
        # 查询所有分类
        categorys = Classification.objects.filter(is_delete=False).order_by("order")
        # 取出第一个分类
        if cate_id == "":
            category = categorys.first()
            cate_id = category.pk
        else:
            # 根据ID查询对应分类
            cate_id = int(cate_id)
            category = Classification.objects.get(pk=cate_id)

        # 查询该分类下的所有商品
        goods_skus = GoodsSKU.objects.filter(is_delete=False, classification=category)
        if order == '':
            order = 0
        order = int(order)

        # 排序
        order_rule = ['pk', '-sale', 'price', '-price', '-create_time']
        goods_skus = goods_skus.order_by(order_rule[order])

        # 获取用户购物车中的总数量
        cart_count = get_cart_count(request)

        context = {
            'categorys': categorys,
            'goods_skus': goods_skus,
            'cate_id': cate_id,
            'order': order,
            'cart_count':cart_count
        }
        return render(request, 'goods/category.html', context=context)

supermarket/templates/goods/index.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    超市
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head1">
        <div class="am-header-left am-header-nav">
            <a href="{% url 'goods:城市' %}" class="" style="color: #fff;">
                <img src="{% static 'images/city.png' %}"/>
                <p style="font-size: 12px; margin-top: -35px;" id="info">全国</p>
            </a>
        </div>
        <h1 class="am-header-title1">
            <div class="search-box">
                <a href="{% url 'goods:校区' %}" class="index-search">南昌大学前湖校区∨</a>
                <!--  <input type="submit" value="" class="search-icon" /> -->
            </div>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url 'goods:消息中心' %}" class="">
                <div class="messgae"><span>10</span></div>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for v in banner %}
            <li><a href="{% url 'goods:商品详情' v.goods_sku.pk %}"><img src="{{ MEDIA_URL }}{{ v.img_url }}"/> </a><p>{{ v.name }}</p></li>
            {% endfor %}

        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav">
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:充值中心' %}" class="">
                    <img src="{% static 'images/icon.png' %}"/>
                    <p>充值</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/icon1.png' %}"/>
                    <p>签到</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:红包' %}" class="">
                    <img src="{% static 'images/icon2.png' %}"/>
                    <p>红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/icon3.png' %}"/>
                    <p>即将上线</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="sq-nav1">
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:零食飞速' %}" class="">
                    <img src="{% static 'images/icon4.png"' %}"/>
                    <p>零食飞速</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:商品列表' '' '' %}" class="">
                    <img src="{% static 'images/icon5.png' %}"/>
                    <p>超市</p>
                </a>
            </div>
        </li>

    </ul>
    <div class="h-line"></div>
    <!--不规则展示-->
    <div class="index-product">
        <div class="index-pro-lf"><a href=""><img src="{% static 'images/s1.png' %}"/></a></div>
        <div class="index-pro-lr"><a href=""><img src="{% static 'images/s2.png' %}"/></a></div>
    </div>
    <div class="product-bot">
        <div class="product-bot-lf"><a href=""><img src="{% static 'images/s3.png' %}"/></a></div>
        <div class="product-bot-lr">
            <div class="top"><a href=""><img src="{% static 'images/s4.png' %}"/></a></div>
            <div class="bot">
                <div class="bot-lf"><a href=""><img src="{% static 'images/s5.png' %}"/></a></div>
                <div class="bot-lr"><a href=""><img src="{% static 'images/s6.png' %}"/></a></div>
            </div>
        </div>
    </div>
    <!--不规则展示-->
    <div class="h-line"></div>
    <!-- 特色专区-->
    <div class="sq-title">
        <img src="{% static 'images/ts.png' %}" width="26"/>
        特色专区
    </div>
    <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default">
    {% for i in goods_sku %}
            <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:商品详情' i.pk %}" class="">
                    <img src=" {{ MEDIA_URL }}{{ i.logo }}"/>
                    <h3 class="am-gallery-title">{{i.goods_spu.spu_name}}&emsp;{{ i.sku_name }}</h3>
                    <div class="am-gallery-desc">￥{{i.price}}</div>
                </a>
            </div>
        </li>
    {% endfor %}


    </ul>
<!--签到-->
<div class="qd-box">
    <div class="popup-title">
        <span>签到成功</span>
        <div class="popup-close"><i class="iconfont">&#xe602</i></div>
    </div>
    <div class="dq-text">
        <img src="{% static 'images/qiandao.png' %}" width="40"/>&nbsp; 您已连续签到3天
    </div>
</div>
{% endblock %}
<!--签到-->



{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:超市首页' %}" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'shopcart:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'order:确认订单' %}}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}


{% block footer_js %}
    <script type="text/javascript"
            src="https://webapi.amap.com/maps?v=1.4.12&key=d36ae53bdb8538d2191b0267bd469bc9&plugin=AMap.CitySearch"></script>
    <script type="text/javascript">
        //获取用户所在城市信息
        function showCityInfo() {
            //实例化城市查询类
            var citysearch = new AMap.CitySearch();
            //自动获取用户IP，返回当前城市
            citysearch.getLocalCity(function (status, result) {
                if (status === 'complete' && result.info === 'OK') {
                    if (result && result.city && result.bounds) {
                        var cityinfo = result.city;
                        document.getElementById('info').innerHTML = cityinfo;
                    }
                } else {
                    document.getElementById('info').innerHTML = result.info;
                }
            });
        }

        showCityInfo();
    </script>
{% endblock %}