blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from myblog.views import BlogIndex

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('myblog.urls',namespace='blog')),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^search/',include('haystack.urls',namespace='search')),
    url(r'^ckeditor/', include("ckeditor_uploader.urls")), ##富文本编辑器
]

blog/myblog/urls.py
from django.conf.urls import url

from myblog.views import BlogIndex, BlogDetail, CommentView

urlpatterns = [
    url(r'^(?P<cate_id>\d*)_{1}(?P<tag_id>\d?)\.html$',BlogIndex.as_view(),name='博客首页'),
    url(r'^detail/(?P<id>\d+)$',BlogDetail.as_view(),name='详情'),
    url(r'^comment/(?P<post_pk>\d+)$',CommentView.as_view(),name='留言')
]

blog/users/urls.py
from django.conf.urls import url

from users.views import RegisterView, LoginView

urlpatterns = [
    url(r'reg',RegisterView.as_view(),name='注册'),
    url(r'login',LoginView.as_view(),name='登录')
]

blog/myblog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


from django.urls import reverse


# 分类
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='类名', )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "类别管理"
        verbose_name_plural = verbose_name


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='标签名称', )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签管理"
        verbose_name_plural = verbose_name


# 文章
class Post(models.Model):
    title = models.CharField(max_length=70, verbose_name='文章标题')
    body = RichTextUploadingField(verbose_name='文章正文')
    created_time = models.DateTimeField(verbose_name='创建时间', )
    modified_time = models.DateTimeField(verbose_name='修改时间', )
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')
    category = models.ForeignKey(Category, verbose_name='文章类别', )
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='文章标签', )
    author = models.ForeignKey(User, verbose_name='文章作者', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:详情', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "文章管理"
        verbose_name_plural = verbose_name

blog/users/models.py
from django.db import models


# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=100, verbose_name='用户名')
    password = models.CharField(max_length=32, verbose_name='密码')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name


class Comment(models.Model):
    text = models.TextField(verbose_name='留言')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    is_delete = models.BooleanField(default=False, verbose_name='是否删除')
    post = models.ForeignKey('myblog.Post', verbose_name='评论')

    def __str__(self):
        return self.text[:20]

    class Mete:
        verbose_name = '评论管理'
        verbose_name_plural = verbose_name

blog/myblog/views.py
from django.core import paginator
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from db.base_view import VerifyLoginView
from myblog.models import Post, Category, Tag


# 首页
from users.forms import CommentForm
from users.models import Comment


class BlogIndex(View):
    def get(self, request, cate_id, tag_id):
        # 查询所有分类
        categorys = Category.objects.all()
        # 取出第一个分类
        if cate_id == "":
            category = categorys.first()
            cate_id = category.pk
        else:
            # 根据分类id查询对应的分类
            cate_id = int(cate_id)
            category = Category.objects.get(pk=cate_id)
        # 查询对应分类下的文章
        posts = Post.objects.filter(category_id=category)
        # 查询所有标签
        tags = Tag.objects.all()
        if tag_id == '':
            tag = tags.first()
            tag_id = tag.pk
        else:
            tag_id = int(tag_id)
            tag = Tag.objects.get(pk=tag_id)
        result = Post.objects.filter(tags=tag)

        # 分页
        paginator = Paginator(posts, 5)  # 每页显示n条记录
        # 获取当前页码数据
        page = request.GET.get('page', 1)  # 当前页码?Page=1
        # 获取对应页码数据
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数 显示第一页
            posts = paginator.page(1)
        except EmptyPage:
            # 页码为空 显示最后一页
            posts = paginator.page(paginator.num_pages)
        context = {
            'posts': posts,
            'result': result,
            'cate_id': cate_id,
            'tag_id': tag_id,
            'categorys':categorys,
            'tags':tags,
        }
        return render(request, 'myblog/index.html', context=context)

    def post(self, request):
        pass


# 详情
class BlogDetail(View):
    def get(self, request, id):
        post = Post.objects.get(pk=id, is_delete=False)
        comment = Comment.objects.filter(post_id=id,is_delete=False)
        categorys = Category.objects.all()
        tags = Tag.objects.all()
        paginator = Paginator(comment, 5)  # 每页显示n条记录
        # 获取当前页码数据
        page = request.GET.get('page', 1)  # 当前页码?Page=1
        # 获取对应页码数据
        try:
            comment = paginator.page(page)
        except PageNotAnInteger:
            # 页码不是整数 显示第一页
            comment = paginator.page(1)
        except EmptyPage:
            # 页码为空 显示最后一页
            comment = paginator.page(paginator.num_pages)
        context = {
            'post': post,
            'comment':comment,
            'categorys':categorys,
            'tags':tags

        }
        return render(request, 'myblog/info.html', context=context)

    def post(self, request):
        pass

class CommentView(VerifyLoginView):
    def get(self,request):
        return render(request,'user/login.html')

    def post(self,request,post_pk):
        try:
            post = Post.objects.filter(pk=post_pk,
                                       is_delete=False
                                       )
        except Post.DoesNotExist:
            return redirect('blog:首页')

        # 接收参数
        data = request.POST
        form = CommentForm(data)
        # 接收用户的id
        user_id = request.session.get("ID")
        # 验证数据的合法性
        if form.is_valid():
            # 获取清洗后的数据
            cleaned = form.cleaned_data
            # 取出清洗后的评论
            text = cleaned.get('text')
            # 保存到数据库
            Comment.objects.create(text=text,post_id=post_pk)
            return redirect('blog:详情' ,post_pk)
        else:
            return redirect('blog:详情', post_pk)

blog/templates/myblog/gbook.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
    <meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青"/>
    <meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/m.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header>
    <div class="logo"><a href="/"><img src="images/logo.png"></a></div>
    <nav id="nav">
        <ul>
            <li><a href="{% url 'blog:博客首页' '' '' %}">网站首页</a></li>
            <li><a href="share.html">我的相册</a></li>
            <li><a href="list.html">我的日记</a></li>
            <li><a href="about.html">关于我</a></li>
        </ul>
    </nav>
    <script>
        window.onload = function () {
            var obj = null;
            var As = document.getElementById('nav').getElementsByTagName('a');
            obj = As[0];
            for (i = 1; i < As.length; i++) {
                if (window.location.href.indexOf(As[i].href) >= 0)
                    obj = As[i];
            }
            obj.id = 'selected'
        }
    </script>
</header>
<div class="mnav">
    <ul>
        <li><a href="index.html">首页</a></li>
        <li><a href="share.html">相册</a></li>
        <li><a href="list.html">日记</a></li>
        <li><a href="about.html">关于</a></li>
    </ul>
</div>
<article>
    <div class="l_box">
        <div class="about_me">
            <h2>关于我</h2>
            <ul>
                <i><img src="{% static 'images/4.jpg' %}"></i>
                <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
            </ul>
        </div>
        <div class="wdxc">
            <h2>我的相册</h2>
            <ul>
                <li><a href="/"><img src="{% static 'images/7.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/8.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/9.jpg' %}"></a></li>
            </ul>
        </div>
    </div>
    <div class="r_box">
        <ul class="about">
            <main class="col-md-12">
                {% for post in posts %}
                    <article class="post post-{{ post.pk }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                                <span class="post-author"><a href="#">作者:{{ post.author }}</a></span>
                                <span class="comments-link"><a
                                        href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} 评论</a></span>
                                <span class="views-count"><a href="#">{{ post.views }}  阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{ post.excerpt }}</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                                        class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>

                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}

                <div class="pagination">
                    <span class="step-links">
                        <ul>
                            {#     如果存在上一页才显示           #}
                            {% if post_list.has_previous %}
                                <a href="?page={{ post_list.previous_page_number }}">上一页</a>
                            {% endif %}

                            {#      循环展示页码          #}
                            {% if post_list.paginator.count %}
                                <span class="current">
                                    {% for p in post_list.paginator.page_range %}
                                        {% if p == post_list.number %}
                                            {{ p }}
                                        {% else %}
                                            <a href="{% url 'blog:首页' %}?page={{ p }}">{{ p }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </span>
                            {% endif %}
                            {#     如果存在下一页才显示           #}
                            {% if post_list.has_next %}
                                <a href="?page={{ post_list.next_page_number }}">下一页</a>
                            {% endif %}


                        </ul>
                     </span>

        </ul>
    </div>
</article>
<footer>
    <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>

</body>
</html>

blog/templates/myblog/index.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>首页_路人甲个人博客 - 一个专注于打酱油个人博客网站</title>
    <meta name="keywords" content="个人博客,路人甲个人博客"/>
    <meta name="description" content="路人甲个人博客 - 一个专注于打酱油个人博客网站"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/m.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header>
    <div class="logo"><a href="/"><img src="{% static 'images/logo.png' %}"></a></div>
    <nav id="nav">
        <ul>
            <li><a href="{% url 'blog:博客首页' '' '' %}">网站首页</a></li>
            <li><a href="">我的相册</a></li>
            <li><a href="list.html">我的日记</a></li>
            <li><a href="about.html">关于我</a></li>
            <li><a href="{% url 'user:登录' %}" data-hover="登录">登录</a></li>
            <li><a href="{% url 'user:注册' %}" data-hover="注册">注册</a></li>
        </ul>
    </nav>
    <script>
        window.onload = function () {
            var obj = null;
            var As = document.getElementById('nav').getElementsByTagName('a');
            obj = As[0];
            for (i = 1; i < As.length; i++) {
                if (window.location.href.indexOf(As[i].href) >= 0)
                    obj = As[i];
            }
            obj.id = 'selected'
        }
    </script>
</header>
<article>
    <div class="l_box">
        <div class="about_me">
            <h2>关于我</h2>
            <ul>
                <i><img src="{% static 'images/about.jpg' %}"></i>
                <p><b>路人甲</b>，一个默默无闻的路人,专注于各种酱油角色</p>
            </ul>
        </div>
        <div class="wdxc">
            <h2>我的相册</h2>
            <ul>
                <li><a href="/"><img src="{% static 'images/7.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/8.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/9.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/10.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/11.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/12.jpg' %}"></a></li>
            </ul>
        </div>
        <div class="search">
            <form action="{% url 'search:haystack_search' %}" method="get" name="searchform" id="searchform">
                <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                       style="color: rgb(153, 153, 153);"
                       onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                       onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                <input name="show" value="title" type="hidden">
                <input name="tempid" value="1" type="hidden">
                <input name="tbname" value="news" type="hidden">
                <input name="Submit" class="input_submit" value="搜索" type="submit">
            </form>
        </div>
        <div class="fenlei">
            <h2>文章分类</h2>
            {% for v in categorys %}
                <ul>
                    <li {% if cate_id == v.pk %} class="current"{% endif %}><a
                            href="{% url 'blog:博客首页' v.pk '' %}">{{ v.name }}</a></li>
                </ul>
            {% endfor %}
        </div>
        <div class="cloud">
            <h2>标签云</h2>
            {% for tag in tags %}
                <ul>
                    <li {% if tag_id == tag.pk %} class="current"{% endif %}><a
                            href="{% url 'blog:博客首页' '' tag.pk %}">{{ tag.name }}</a>
                </ul>
            {% endfor %}
        </div>
    </div>
    <div class="r_box">
        {% for post in posts %}
            <li><i><a href="/"><img src="{% static 'images/1.jpg' %}"></a></i>
                <h3><a href="{% url 'blog:详情' post.pk %}">{{ post.title }}</a></h3>
                <p>{{ post.body }}</p>
            </li>
        {% endfor %}
        <ul>
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">上一页</a>
            {% endif %}
            {% if posts.paginator.count %}
                <span class="current">
                                    {% for v in posts.paginator.page_range %}
                                        {% if v == posts.number %}
                                            {{ v }}
                                        {% else %}
                                            <a href="{% url 'blog:博客首页' '' '' %}?page={{ v }}">{{ v }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </span>
            {% endif %}
            {#如果存在下一页才显示#}
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">下一页</a>
            {% endif %}


        </ul>
    </div>
</article>
</body>
</html>

blog/templates/myblog/info.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>首页_个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
    <meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青"/>
    <meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/info.css' %}" rel="stylesheet">
    <link href="{% static 'css/m.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header>
    <div class="logo"><a href="/"><img src="{% static 'images/logo.png' %}"></a></div>
    <nav id="nav">
        <ul>
            <li><a href="{% url 'blog:博客首页' '' '' %}">网站首页</a></li>
            <li><a href="">我的相册</a></li>
            <li><a href="list.html">我的日记</a></li>
            <li><a href="about.html">关于我</a></li>
            <li><a href="{% url 'user:登录' %}" data-hover="登录">登录</a></li>
            <li><a href="{% url 'user:注册' %}" data-hover="注册">注册</a></li>
        </ul>
    </nav>
    <script>
        window.onload = function () {
            var obj = null;
            var As = document.getElementById('nav').getElementsByTagName('a');
            obj = As[0];
            for (i = 1; i < As.length; i++) {
                if (window.location.href.indexOf(As[i].href) >= 0)
                    obj = As[i];
            }
            obj.id = 'selected'
        }

    </script>
    <script type="text/javascript">

        $(document).ready(function (e) {
            t = $('.guanzhu').offset().top;

            mh = $('.infosbox').height();
            fh = $('.guanzhu').height();

            $(window).scroll(function (e) {
                s = $(document).scrollTop();
                if (s > t - 10) {
                    $('.guanzhu').css('position', 'fixed');
                    $('.guanzhu').css('background', 'fff');
                    if (s + fh > mh) {
                        $('.guanzhu').css('top', mh - s - fh + 'px');
                    }
                } else {
                    $('.guanzhu').css('position', '');
                }

            })
        });

    </script>
</header>
<article>
    <div class="l_box">
        <div class="about_me">
            <h2>关于我</h2>
            <ul>
                <i><img src="{% static 'images/about.jpg' %}"></i>
                <p><b>路人甲</b>，一个默默无闻的路人,专注于各种酱油角色</p>
            </ul>
        </div>
        <div class="wdxc">
            <h2>我的相册</h2>
            <ul>
                <li><a href="/"><img src="{% static 'images/7.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/8.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/9.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/10.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/11.jpg' %}"></a></li>
                <li><a href="/"><img src="{% static 'images/12.jpg' %}"></a></li>
            </ul>
        </div>
        <div class="search">
            <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                       style="color: rgb(153, 153, 153);"
                       onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                       onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                <input name="show" value="title" type="hidden">
                <input name="tempid" value="1" type="hidden">
                <input name="tbname" value="news" type="hidden">
                <input name="Submit" class="input_submit" value="搜索" type="submit">
            </form>
        </div>
        <div class="fenlei">
            <h2>文章分类</h2>
            {% for v in categorys %}
                <ul>
                    <li {% if cate_id == v.pk %} class="current"{% endif %}><a
                            href="{% url 'blog:博客首页' v.pk '' %}">{{ v.name }}</a></li>
                </ul>
            {% endfor %}
        </div>
        <div class="cloud">
            <h2>标签云</h2>
            {% for tag in tags %}
                <ul>
                    <li {% if tag_id == tag.pk %} class="current"{% endif %}><a
                            href="{% url 'blog:博客首页' '' tag.pk %}">{{ tag.name }}</a>
                </ul>
            {% endfor %}
        </div>
    </div>
    <div class="infosbox">
        <div class="newsview">
            <h3 class="news_title">{{ post.title }}</h3>
            <div class="bloginfo">
                <ul>
                    <li class="author">作者：{{ post.author }}<a href="/"></a></li>
                    <li class="lmname"><a href="/">{{ post.title }}</a></li>
                    <li class="timer">时间：{{ post.created_time }}</li>
                    <li class="view">4567人已阅读</li>
                </ul>
            </div>
            <div class="tags"><a href="/" target="_blank">个人博客</a> &nbsp; <a href="/" target="_blank">小世界</a></div>
            <div class="news_about"><strong></strong>{{ post.body }}</div>
            <div class="news_con">
                <br><br>
                &nbsp;
            </div>
        </div>
        <div class="share">
        </div>
        <div class="nextinfo">
        </div>
        <div class="news_pl">
            <h3>发表评论</h3>
            <form action="{% url 'blog:留言' post.pk %}" method="post" class="comment-form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <label for="id_comment">评论：</label>
                        <textarea name="text" id="id_comment" required></textarea>
                        <button type="submit" class="comment-btn">发表</button>
                    </div>
                </div>
            </form>
            <h2>文章评论</h2>
            {% for x in comment %}
                <div class="comment">
                    <div class="col-md-13">
                        <ul>
                            <li>评论时间:{{ x.create_time }}</li>
                            <li>内容:{{ x.text }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
            <ul>
                {% if comment.has_previous %}
                    <a href="?page={{ comment.previous_page_number }}">上一页</a>
                {% endif %}
                {% if comment.paginator.count %}
                    <span class="current">
                                    {% for v in comment.paginator.page_range %}
                                        {% if v == comment.number %}
                                            {{ v }}
                                        {% else %}
                                            <a href="{% url 'blog:详情' post.id %}?page={{ v }}">{{ v }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </span>
                {% endif %}
                {#如果存在下一页才显示#}
                {% if comment.has_next %}
                    <a href="?page={{ comment.next_page_number }}">下一页</a>
                {% endif %}


            </ul>
        </div>
    </div>
</article>
</body>
</html>