supermarket/apps/user/urls.py
from django.conf.urls import url

from user.views import RegisterView, LoginView, CenterView, MyInfoView, safe, RePassView, SendMailView, AddressView, \
    AddressList, ForgetView

urlpatterns = [
    url(r'^reg$', RegisterView.as_view(), name='注册'),
    url(r'^login$', LoginView.as_view(), name='登录'),
    url(r'^center', CenterView.as_view(), name='个人中心'),
    url(r'^myinfo', MyInfoView.as_view(), name='个人资料'),
    url(r'^safe', safe, name='安全设置'),
    url(r'^address', AddressView.as_view(), name='收货地址添加'),
    url(r'^add_list',AddressList.as_view(),name='收货地址'),
    url(r'^sendmail', SendMailView.as_view(), name='发送信息'),
    url(r'^forget', ForgetView.as_view(), name='忘记密码'),
    url(r'^repass', RePassView.as_view(), name='修改密码'),
]

supermarket/supermarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import ShopView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^orders/', include('orders.urls', namespace='order')),
    url(r'^shopcart/', include('shopcart.urls', namespace='shopcart')),
    url(r"^$", ShopView.as_view(), name='首页'),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls',namespace='search')),
]

supermarket/apps/user/forms.py
from django import forms
from django.core import validators
from django.core.validators import RegexValidator
from django_redis import get_redis_connection

from user import set_password
from user.models import User, AddAddress


# 注册
class RegisterModelForm(forms.ModelForm):
    password = forms.CharField(max_length=16,
                               min_length=6,
                               error_messages={
                                   'required': '密码不能为空',
                                   'min_length': '密码不能小于6位',
                                   'max_length': '密码不能大于16位'
                               })
    repassword = forms.CharField(max_length=16,
                                 min_length=6,
                                 error_messages={
                                     'required': '密码不能为空',
                                     'min_length': '密码不能小于6位',
                                     'max_length': '密码不能大于16位'
                                 })

    captcha = forms.CharField(max_length=6,
                              error_messages={
                                  'required': "验证码必须填写"
                              })

    agree = forms.BooleanField(error_messages={
        'required': '必须同意用户协议'
    })

    class Meta:
        model = User
        fields = ['phone']

        error_messages = {
            'phone': {
                'required': '手机号不能为空',
                'max_length': '手机号长度不能大于11位',
                'min_length': '手机号长度不能小于11位'
            }
        }

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        flag = User.objects.filter(phone=phone).exists()
        if flag:
            raise forms.ValidationError('手机号已注册')
        else:
            return phone

    def clean_verify_code(self):
        # 表单传入的验证码
        verify_code = self.cleaned_data.get('verify_code')
        sid_verify_code = self.data.get('sid_verify_code')
        if int(verify_code) != sid_verify_code:
            raise forms.ValidationError("验证码输入有误")
        else:
            return verify_code

    def clean(self):
        password = self.cleaned_data.get('password', '')
        repassword = self.cleaned_data.get('repassword')
        if password and repassword and password != repassword:
            raise forms.ValidationError({'repassword': '密码不一致'})
        try:
            captcha = self.cleaned_data.get('captcha')
            phone = self.cleaned_data.get('phone', '')
            # 获取redis中的
            r = get_redis_connection()
            random_code = r.get(phone)  # 二进制, 转码
            random_code = random_code.decode('utf-8')
            # 比对
            if captcha and captcha != random_code:
                raise forms.ValidationError({"captcha": "验证码输入错误!"})
        except:
            raise forms.ValidationError({"captcha": "验证码输入错误!"})
        return self.cleaned_data


# 登录
class LoginModelForm(forms.ModelForm):
    password = forms.CharField(max_length=16,
                               min_length=6,
                               error_messages={
                                   'required': '密码不能为空',
                                   'min_length': '密码不能小于6位',
                                   'max_length': '密码不能大于16位'
                               })

    class Meta:
        model = User
        fields = ['phone']
        error_messages = {
            'phone': {
                'required': '手机号不能为空',
                'max_length': '手机号长度不能大于11位',
                'min_length': '手机号长度不能小于11位'
            }
        }

    def clean(self):
        phone = self.cleaned_data.get('phone')
        try:
            user = User.objects.get(phone=phone)
        except User.DoesNotExist:
            raise forms.ValidationError({'phone': '手机号错误'})

        password = self.cleaned_data.get('password')
        if user.password != set_password(password):
            raise forms.ValidationError({'password': '密码错误'})

        self.cleaned_data['user'] = user
        return self.cleaned_data


# 个人信息
class MyInfoModelForm(forms.ModelForm):
    username = forms.CharField(max_length=16,
                               min_length=6,
                               error_messages={
                                   'required': '用户名不能为空',
                                   'min_length': '用户名不能小于6位',
                                   'max_length': '用户名不能大于16位'
                               })

    class Meta:
        model = User
        exclude = ['username']

# 忘记密码
class ForgetForm(forms.Form):
    phone = forms.CharField(max_length=11,
                            error_messages={'required': '请填写手机号!'},
                            validators=[RegexValidator(r'^1[3-9]\d{9}$', message="手机号码格式错误!")]
                            )
    password2 = forms.CharField(max_length=20,
                                min_length=6,
                                error_messages={
                                    'required': '请填写密码!',
                                    'min_length': '请输入至少六个字符!',
                                    'max_length': '请输入小于或等于二十个字符!'
                                })
    repassword2 = forms.CharField(max_length=20,
                                  min_length=6,
                                  error_messages={
                                      'required': '这是必填选项!',
                                      'min_length': '请输入至少六个字符!',
                                      'max_length': '请输入小于或等于二十个字符!'
                                  })
    # 验证码
    captcha = forms.CharField(max_length=6,
                              error_messages={
                                  'required': "验证码必须填写!"
                              })

    def clean(self):
        pwd = self.cleaned_data.get("password")  # 密码
        repwd = self.cleaned_data.get("repassword")  # 重复密码
        if pwd and repwd and pwd != repwd:
            raise forms.ValidationError({"repassword": "两次密码不一致,请重新输入!"})
        # 返回,返回整个清洗后的数据
        return self.cleaned_data

    def clean_mobile(self):  # 验证用户名是否存在
        phone = self.cleaned_data.get('phone')
        flag = User.objects.filter(phont=phone).exists()
        if flag:
            # 存在 正确
            return phone
        else:
            raise forms.ValidationError("该手机未注册,请注册!")

# 修改密码
class PasswordForm(forms.Form):
    password = forms.CharField(max_length=20,
                               min_length=6,
                               error_messages={
                                   'required': '请填写密码!',
                                   'min_length': '请输入至少六个字符!',
                                   'max_length': '请输入小于或等于二十个字符!'
                               })
    password2 = forms.CharField(max_length=20,
                                min_length=6,
                                error_messages={
                                    'required': '请填写修改密码!',
                                    'min_length': '请输入至少六个字符!',
                                    'max_length': '请输入小于或等于二十个字符!'
                                })
    repassword2 = forms.CharField(max_length=20,
                                  min_length=6,
                                  error_messages={
                                      'required': '这是必填选项!',
                                      'min_length': '请输入至少六个字符!',
                                      'max_length': '请输入小于或等于二十个字符!'
                                  })

    def clean(self):
        pwd = self.cleaned_data.get("password2")  # 密码
        repwd = self.cleaned_data.get("repassword2")  # 重复密码
        if pwd and repwd and pwd != repwd:
            raise forms.ValidationError({"repassword2": "两次密码不一致,请重新输入!"})
        # 返回,返回整个清洗后的数据
        return self.cleaned_data


# 收货地址
class AddressForm(forms.ModelForm):
    class Meta:
        model = AddAddress
        exclude = ['create_time', 'update_time', 'is_delete', 'user']

        error_messages = {
            'name': {
                'required': "请填写用户名！",
            },
            'phone': {
                'required': "请填写手机号码！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    def clean(self):
        # 验证如果数据库里地址已经超过6六表报错
        cleaned_data = self.cleaned_data
        count = AddAddress.objects.filter(user_id=self.data.get("user_id")).count()
        if count >= 6:
            raise forms.ValidationError({"harea": "收货地址最多只能保存6条"})
        if cleaned_data.get('isdefault'):
            AddAddress.objects.filter(user_id=self.data.get("user_id")).update(isdefault=False)

        return cleaned_data

supermarket/apps/user/views.py
import random
import re
import uuid

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.utils.decorators import method_decorator

from django.views import View
from django_redis import get_redis_connection

from db.base_view import BaseVerifyView
from shopcart.helper import json_msg
from user import set_password
from user.forms import LoginModelForm, RegisterModelForm, MyInfoModelForm, AddressForm, ForgetForm
from user.helper import check_login, login, send_sms
from user.models import User, AddAddress


# 个人中心
class CenterView(View):
    def get(self, request):
        return render(request, 'user/member.html', )

    def post(self, request):
        return render(request, 'user/member.html')


# 个人信息(完成)
class MyInfoView(View):
    def get(self, request):
        id = request.session.get('ID')
        data = User.objects.get(pk=id)
        context = {
            'users': data
        }
        return render(request, 'user/info.html', context=context)

    def post(self, request):
        if request.method == "POST":
            id = request.session.get('ID')
            username = request.POST.get('username')
            head = request.POST.get('head')
            sex = request.POST.get('sex')
            school = request.POST.get('school')
            address = request.POST.get('address')
            hometown = request.POST.get('hometown')
            data = {
                'head': head,
                'username': username,
                'sex': sex,
                'school': school,
                'address': address,
                'hometown': hometown
            }
            User.objects.filter(pk=id).update(**data)
            return redirect('user:个人中心')
        else:
            return render(request, "user/info.html", )


# 注册(完成)
class RegisterView(View):
    def get(self, request):
        return render(request, 'user/reg.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        form = RegisterModelForm(data)
        # 验证判断
        if form.is_valid():
            # 判断通过,保存数据并进行跳转
            cleaned_data = form.cleaned_data
            user = User()
            user.phone = cleaned_data.get('phone')
            user.password = set_password(cleaned_data.get('password'))
            user.save()
            # 注册成功,跳转登录
            return redirect('user:登录')
        else:
            # 验证失败,报错,返回注册界面
            return render(request, 'user/reg.html', {'form': form})


# 登录(完成)
class LoginView(View):
    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        form = LoginModelForm(data)
        if form.is_valid():
            # 根据参数进行判断,通过跳转商品列表
            user = form.cleaned_data.get('user')
            login(request, user)
            referer = request.session.get('referer')
            if referer:
                # 跳转回去
                # 删除session
                del request.session['referer']
                return redirect(referer)
            else:
                # 合成响应, 跳转到个人中心
                return redirect('user:个人中心')
        else:
            # 判断不通过,报错
            return render(request, 'user/login.html', {'form': form})


# 发送短信验证(完成)
class SendMailView(View):
    def get(self, request):
        pass

    def post(self, request):
        # 接收参数
        phone = request.POST.get('phone', '')
        # 判断电话号码是否符合格式
        result = re.search('^1[3-9]\d{9}$', phone)
        if result is None:
            return JsonResponse({'error': 1, 'errmsg': '电话格式错误'})
        # 生成验证码
        num = ''.join([str(random.randint(0, 9)) for v in range(4)])
        print(num)
        r = get_redis_connection()
        # 保存验证码
        r.set(phone, num)
        r.expire(phone, 60)
        # 获取手机号的发送次数
        key_times = '{}_times'.format(phone)
        now_times = r.get(key_times)
        if now_times is None or now_times < 5:
            r.incr(key_times)
            r.expire(key_times, 3600)
        else:
            return JsonResponse({'error': 1, 'errmsg': '发送次数过多'})
            # 导入第三方
        __business_id = uuid.uuid1()
        params = "{\"code\":\"%s\",\"product\":\"打酱油的\"}" % num
        rs = send_sms(__business_id, phone, "注册验证", "SMS_2245271", params)
        print(rs.decode('utf-8'))

        return JsonResponse({'error': 0})

# 修改密码
class RePassView(View):
    def get(self, request):
        return render(request, 'user/forgetpassword.html')

    def post(self, request):
        # 接收参数
        data = request.POST

        # 验证数据的合法性
        form = ForgetForm(data)
        if form.is_valid():
            # 获取清洗后的数据
            cleaned = form.cleaned_data
            # 通过id查询数据
            user_id = request.session.get('ID')
            phone = cleaned.get('phone')
            password2 = set_password(cleaned.get('password2'))
            # 修改到数据库
            if User.objects.filter(phone=phone, id=user_id).exists():
                # 更新密码
                User.objects.filter(id=user_id).update(password=password2)
                # 跳转到登录页
                return redirect('users:登录')
        else:
            # 错误
            return render(request, 'user/forgetpassword.html', context={'errors': form.errors, })


# 忘记密码
class ForgetView(View):
    """忘记密码"""

    def get(self, request):
        return render(request, 'user/forgetpassword.html')

    def post(self, request):
        # 接收参数
        data = request.POST

        # 验证数据的合法性
        form = ForgetForm(data)
        if form.is_valid():
            # 获取清洗后的数据
            cleaned = form.cleaned_data
            # 将密码进行加密
            # 通过id查询数据
            user_id = request.session.get('ID')
            # 取出清洗后的手机号
            phone = cleaned.get('phone')
            # 取出清洗后的密码
            password2 = set_password(cleaned.get('password2'))
            # 修改到数据库
            # 验证原密码是否存在,不能用get,用filter
            if User.objects.filter(phone=phone, id=user_id).exists():
                # 更新密码
                User.objects.filter(id=user_id).update(password=password2)
                # 跳转到登录页
                return redirect('users:登录')
        else:
            # 错误
            return render(request, 'user/forgetpassword.html', context={'errors': form.errors, })


# 安全中心
def safe(request):
    return render(request, 'user/saftystep.html')


# 添加收货地址
class AddressView(BaseVerifyView):
    def get(self, request):
        return render(request, 'user/address.html')

    def post(self, request):
        # 接收参数,并转换成字典
        data = request.POST.dict()

        # 字典保存用户
        data['user_id'] = request.session.get("ID")  # form自动转换功能

        # 验证参数
        form = AddressForm(data)
        if form.is_valid():
            form.instance.user = User.objects.get(pk=data['user_id'])
            form.save()
            return JsonResponse(json_msg(0, '添加成功'))
        else:
            return JsonResponse(json_msg(1, '添加失败', data=form.errors))


# 收获地址列表
class AddressList(BaseVerifyView):
    def get(self, request):
        # 获取用户的收货地址
        user_id = request.session.get("ID")
        user_addresses = AddAddress.objects.filter(user_id=user_id, is_delete=False).order_by("-isdefault")

        # 渲染数据
        context = {
            'addresses': user_addresses
        }
        return render(request, 'user/address_list.html', context=context)

supermarket/templates/user/login.html
{% extends 'common/parent.html' %}
{% load static %}

{% block title %}
    登录
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div style="height: 49px;"></div>
    <div style="height: 3rem;"></div>
    <input type="text" name="phone" id="phone" value="{{ request.POST.phone }}" placeholder="请输入用户名/手机号" class="login-name">
    <p class="am-text-danger">{{ form.errors.phone.0 }}</p>
    <input type="password" name="password" id="password" value="{{ request.POST.password }}" placeholder="请输入密码" class="login-password">
    <p class="am-text-danger">{{ form.errors.password.0 }}</p>
    <input type="submit" class="login-btn" value="我要登录">
    <div class="agree">

        <a href="{% url 'user:注册' %}">免费注册</a>
        <a href="{% url 'user:忘记密码' %}" class="forget">忘记密码？</a>
    </div>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>
</form>
{% endblock %}

supermarket/templates/user/reg.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    注册
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div style="height: 49px;"></div>
        <div style="height: 3rem;"></div>
        <input type="text" name="phone" id="phone" value="{{ request.POST.phone }}" placeholder="请输入手机号"
               class="login-name">
        <p class="am-text-danger">{{ form.errors.phone.0 }}</p>

        <input type="password" name="password" value="{{ request.POST.password }}" placeholder="请输入密码"
               class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>

        <input type="password" name="repassword" value="{{ request.POST.repassword }}" placeholder="确认密码"
               class="login-name">
        <p class="am-text-danger">{{ form.errors.repassword.0 }}</p>
        <div class="yzm" style="margin-top: 1.5rem;">
	    	<input type="text" name="verify_code" class="reg-yzm" value="{{ request.POST.verify_code }}" placeholder="输入验证码"   />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
        <p class="am-text-danger">{{ form.errors.captcha.0 }}</p>

        <input type="submit" class="login-btn" value="立即注册">
        <div class="agree">
            <input type="checkbox" name="checkbox" value="同意" checked="">&nbsp;同意
            <a href="" class="xy">《用户协议》</a>
            <div class="r-login">已有账号，请<a href="{% url 'user:登录' %}" class="l-login">登录</a></div>
        </div>
    </form>
{% endblock %}

{% block footer_js %}
    <script type="application/javascript">
        $(function () {
            绑定事件
            $('.yzm-hq').on('click', function (){
                console.debug(111);
                获取手机号
                var phone = $("#phone").val();
                var reg = /^1[3-9]\d{9}$/;
                if (!reg.test(phone)) {
                    alert("手机号码格式错误!");
                    return;
                }
                var self = this;
                发送ajax请求
                $.ajax({
                    type: 'post',
                    url: '{% url "user:发送信息" %}',
                    data: {'phone': phone, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success: function (data) {
                        if (data.error == 0) {
                            $(self).css('background-color', 'gray');
                            $(self).prop('disabled', true);
                            var time = 60;
                            var msg = time + '秒后重新发送';
                            $(self).val(msg);
                            var timer = window.setInterval(function () {
                                time -= 1;
                                if (time == 0){
                                    //1. 按钮颜色变绿
                                    $(self).css("background-color","#76bb2a");
                                    //2. 按钮能再点击
                                    $(self).prop('disabled',false);
                                    //3. 返回原来的提示文字
                                    $(self).val("获取验证码");
                                    //4. 清除定时
                                    window.clearInterval(timer);
                                    //返回
                                    return;
                                }
                                msg = time + "秒后重新发送";
                                $(self).val(msg);
                            },60);
                        } else {
                            alert(data.errmsg)
                        }
                    }
                })

            })
        })
    </script>
{% endblock %}